name: update_and_publish

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  generate:
    name: Generate GTFS-Realtime bindings
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Setup Dart
        uses: dart-lang/setup-dart@v1.3

      - name: Check Dart version
        run: dart --version

      - name: Download newest GTFS-Realtime contract
        run: curl https://raw.githubusercontent.com/google/transit/master/gtfs-realtime/proto/gtfs-realtime.proto --output gtfs-realtime.proto

      - name: Install protoc_plugin plugin
        run: dart pub global activate protoc_plugin

      - name: Generate dart GTFS-Realtime bindings
        run: protoc --dart_out=lib/src gtfs-realtime.proto

      - name: Install dependencies
        run: dart pub get

      - name: Format code
        run: dart format .

      - name: Analyze
        run: dart analyze

      - name: Test
        run: dart test

      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          message: Update GTFS-Realtime bindings
          empty: true

