name: Test

on:
  pull_request:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Dart
        uses: dart-lang/setup-dart@v1.3

      - name: Check Dart version
        run: dart --version

      - name: Install dependencies
        run: dart pub get

      - name: Analyze
        run: dart analyze

      - name: Test
        run: dart test
